services:
  postgres:
    image: postgres:16-alpine # Using a specific version and alpine for smaller image size
    container_name: aletheia-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data in a named volume
    restart: always # Ensure the container restarts if it stops

volumes:
  postgres_data: # Define the named volume